Repository RobotecAI/o3de-ros2-gem, pull requests merged in 2022-09, with the labels that each got.

#175 Added material assigment to links with wheel
  Assets/Materials/wheel_material.physxmaterial
  Code/Source/RobotImporter/URDF/CollidersMaker.cpp
  Code/Source/RobotImporter/URDF/CollidersMaker.h
  Code/Source/RobotImporter/URDF/JointsMaker.cpp
  Code/Source/RobotImporter/URDF/JointsMaker.h
  Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp
  Code/Source/RobotImporter/Utils/RobotImporterUtils.h
  Code/Tests/UrdfParserTest.cpp
  Code/ros2_files.cmake
  Code/ros2_tests_files.cmake
Labels: enhancement

#187 Disabled computation of intertia parameters in URDF importer
  Code/Source/RobotImporter/URDF/InertialsMaker.cpp
Labels: enhancement

#188 Fix Editor crashes on URDF prefab overwite and import non-valid URDF
  Code/Source/RobotImporter/URDF/RobotImporter.cpp
  Code/Source/RobotImporter/URDF/RobotImporter.h
  Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp
Labels: bug

#222 Created documentation related to Robot Control and Vehicle Model
  docs/design/vehicle_dynamics/diagrams/ROSVehicleDynamics_planned.graphml
  docs/design/vehicle_dynamics/diagrams/ROSVehicleDynamics_planned.png
  docs/guides/ros2-gem.md
  docs/guides/static/diagrams/diagram_ros2_gem.png
  docs/guides/static/diagrams/diagram_ros2_gem_yEd.graphml
Labels: documentation

#220 Added support for prismatic joint in URDF importer
  Code/Source/RobotImporter/URDF/JointsMaker.cpp
Labels: enhancement

#247 Added routine to access components without specifying if wrapped
  Code/Source/Camera/CameraSensor.h
  Code/Source/Camera/ROS2CameraSensorComponent.cpp
  Code/Source/Frame/ROS2FrameComponent.cpp
  Code/Source/GNSS/ROS2GNSSSensorComponent.cpp
  Code/Source/Imu/ROS2ImuSensorComponent.cpp
  Code/Source/Lidar/ROS2LidarSensorComponent.cpp
  Code/Source/ROS2GemUtilities.cpp
  Code/Source/ROS2GemUtilities.h
  Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp
  Code/Source/RobotImporter/Utils/RobotImporterUtils.cpp
  Code/Source/RobotImporter/Utils/RobotImporterUtils.h
  Code/Source/Sensor/ROS2SensorComponent.cpp
  Code/ros2_files.cmake
Labels: bug
